name: CD Frontend

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image (frontend)
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vbstaff-frontend:${{ github.ref_name }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vbstaff-frontend:latest \
            -f Dockerfile \
            .

      - name: Push Docker image (frontend)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vbstaff-frontend:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vbstaff-frontend:latest

      - name: Notify Watchtower
        run: |
          curl -X POST http://${{ secrets.WATCHTOWER_HOST }}:${{ secrets.WATCHTOWER_PORT }}/v1/update \
          -H "Authorization: Bearer ${{ secrets.WATCHTOWER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "service": "frontend",
                "image": "${{ secrets.DOCKERHUB_USERNAME }}/vbstaff-frontend:${{ github.ref_name }}"
              }'